spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:voting;TRACE_LEVEL_FILE=4;
    #url: jdbc:h2:mem:voting;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS voting;
    #tcp: jdbc:h2:tcp://localhost:9092/mem:voting;OLD_INFORMATION_SCHEMA=TRUE
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none # not to ignore data.sql #TODO: change to create
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        jdbc.batch_size: 20

  h2:
    console:
      enabled: true

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
        orm:
          jpa: DEBUG
        transaction: DEBUG

    root: WARN
    org.example: DEBUG
